In [2]:
import numpy as np

In [3]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(np_array)

numpy.ndarray

### Single Element Indexing

Return the 2nd row's 3rd value

In [6]:
np_array[1]

array([4, 5, 6])

The following are equivalent

In [7]:
np_array[1][2]

6

In [8]:
np_array[1, 2]

6

### Slicing and striding
You can also access specific colums only using the following

In [9]:
np_array[:, 2]

array([3, 6, 9])

In [10]:
np_array[0:2:1, 1:4:2]

array([[2],
       [5]])

### Boolean Indexing

Return all the rows where the first value is smaller than 5

In [9]:
np_array[np_array[:, 0] < 5]

array([[1, 2, 3],
       [4, 5, 6]])

### Fancy Indexing

Return the 3rd and 1st rows only.

In [10]:
np_array[[2, 0]]

array([[7, 8, 9],
       [1, 2, 3]])

In [20]:
np_array[[0, 2], [2, 0]]

array([3, 7])