In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([-1, 5, 6])

In [4]:
print(np.exp(arr_1))
print(np.log(arr_1))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [7]:
print(np.ceil(arr_1))
print(np.floor(arr_1))
print(np.around(arr_1))

[1. 2. 3.]
[1. 2. 3.]
[1 2 3]


In [10]:
print(np.min(arr_1))
print(np.max(arr_1))
print(np.sum(arr_1))
print(np.mean(arr_1))
print(np.std(arr_1))
print(np.argmin(arr_1))
print(np.argmax(arr_1))

1
3
6
2.0
0.816496580927726
0
2


In [3]:
np.cov(arr_1, arr_2)

array([[ 1.        ,  3.5       ],
       [ 3.5       , 14.33333333]])

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.histogram(arr, 3)

(array([3, 3, 4]), array([ 1.,  4.,  7., 10.]))

In [6]:
np.percentile(arr, [10, 90])

array([1.9, 9.1])

In [12]:
print(np.add(arr_1, arr_2))
print(np.subtract(arr_1, arr_2))
print(np.multiply(arr_1, arr_2))
print(np.divide(arr_1, arr_2))

[0 7 9]
[ 2 -3 -3]
[-1 10 18]
[-1.   0.4  0.5]


In [13]:
print(np.minimum(arr_1, arr_2))
print(np.maximum(arr_1, arr_2))

[-1  2  3]
[1 5 6]
