In [2]:
import numpy as np

- Search

In [3]:
nums = np.array(range(10))

In [4]:
np.where(nums < 5, nums*10, nums)

array([ 0, 10, 20, 30, 40,  5,  6,  7,  8,  9])

- Sort

In [5]:
array = np.array([[1, 1, 2, 2],
                  [2, 2, 3, 3],
                  [2, 2, 1, 1]])

In [6]:
np.sort(array, axis=1)

array([[1, 1, 2, 2],
       [2, 2, 3, 3],
       [1, 1, 2, 2]])

In [7]:
np.sort(array, axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 3, 3]])

- Unique

In [8]:
np.unique(array)

array([1, 2, 3])